app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



Route::auth();


Route::get('/', 'HomeController@index');

Route::get('/homepage-2', 'HomeController@homepage2');


Route::post('create-tickets', [
	'as' => 'create.ticket',
	'uses' => 'TicketController@createTicket'
]);


// Ticket Route
Route::group(['middleware' => 'auth'], function() {

//	Route::post('create-tickets', [
//		'as' => 'create.ticket',
//		'uses' => 'TicketController@createTicket'
//	]);

	Route::get('edit-ticket/{id}', [
		'as' => 'edit.ticket', 
		'uses' => 'TicketController@getEditTickets'
	]);

	Route::post('edit-tickets/{id}', [
		'as' => 'edit.post.ticket', 
		'uses' => 'TicketController@postEditTickets'
	]);

	Route::get('all-tickets', [
		'as' => 'all.tickets', 
		'uses' => 'TicketController@allTickets'
	]);

	Route::get('ticket/{id}/{subject}', [
		'as' => 'single.ticket', 
		'uses' => 'TicketController@showTickets'
	]);

	// Ticket remove
	Route::post('/ticket/remove', [
		'as'	=> 	'dashboard.ticket.remove',
		'uses'	=> 	'Backend\TicketController@removeTicket',
	]);

});


// Reply Route
Route::group(['middleware' => 'auth'], function() {

	Route::post('{id}/create-reply', [
		'as' => 'create.reply', 
		'uses' => 'ReplyController@createReply'
	]);

	Route::post('/remove-reply/{id}', [
		'as' => 'remove.reply', 
		'uses' => 'ReplyController@removeReply'
	]);

});

// Profile Settings
Route::group(['middleware' => 'auth'], function() {

	Route::get('profile/settings', [
		'as' => 'proifle.settings', 
		'uses' => 'HomeController@settings'
	]);

	 // Update profile
	Route::post('/profile/update', [
		'as'	=> 	'profile.update',
		'uses'	=> 	'Backend\SettingsController@profileUpdate',
	]);


});

//////////////////////
// Dashboard Routes //
//////////////////////
Route::group(['prefix' => 'dashboard', 'middleware' => ['auth', 'role:admin|staff'], 'namespace' => 'Backend'], function() {

	Route::get('/', [
		'as' => 'dashboard.index', 
		'uses' => 'DashboardController@index'
	]);

	Route::post('/get-authenticated-user', [
		'as' => 'get.auth.user', 
		'uses' => 'DashboardController@getAuthUser'
	]);


	/////////////////////////////
	// Dashboard Ticket Routes //
	/////////////////////////////
	Route::get('/tickets/{view}', [
		'as'	=> 	'dashboard.tickets',
		'uses'	=> 	'TicketController@tickets',
	]);

	Route::get('/tickets', function() {
		return redirect('/dashboard/tickets/all');
	});

	Route::get('/tickets/{id}/{subject}', [
		'as' => 'dashboard.single.ticket', 
		'uses' => 'TicketController@showTickets'
	]);

	// assign ticket to staff
	Route::post('/assign/ticket/{id}', [
		'as'	=> 	'ticket.assign.user',
		'uses'	=> 	'TicketController@assignTicket',
	]);

	// update ticket status
	Route::post('/update/ticket/{id}/status', [
		'as'	=> 	'update.ticket.status',
		'uses'	=> 	'TicketController@updateStatus',
	]);



	// Ticket search
	Route::get('/ticket/search', [
		'as'	=> 	'dashboard.ticket.search',
		'uses'	=> 	'TicketController@searchTicket',
	]);


	///////////////////////////////////
	// Dashboard Noticiations Routes //
	///////////////////////////////////

	// Remove single notification

	Route::post('/remove/single/notification', [
		'as'	=> 	'remove.single.notification',
		'uses'	=> 	'NotificationController@removeNotif',
	]);

	// Remove all notification
	Route::post('/remove/all/notification', [
		'as'	=> 	'remove.all.notification',
		'uses'	=> 	'NotificationController@removeAllNotif',
	]);

	///////////////////////////////////////
	// Dashboard Staff and Clients route //
	///////////////////////////////////////


	// Dashbaord Staffs
	Route::get('/staffs/all', [
		'as'	=> 	'dashboard.staffs.all',
		'uses'	=> 	'StaffController@allStaffs',
	]);

	// Staff create
	Route::get('/staffs/create', [
		'as'	=> 	'dashboard.staffs.create',
		'uses'	=> 	'StaffController@getCreate',
	]);

	// Staff Create
	Route::post('/staffs/create', [
		'as'	=> 	'dashboard.staffs.postCreate',
		'uses'	=> 	'StaffController@create',
	]);

	// Get staff edit ajax result
	Route::post('/staffs/edit', [
		'as'	=> 	'dashboard.staffs.getEdit',
		'uses'	=> 	'StaffController@getEdit',
	]);

	// Staff Update
	Route::post('/staffs/update', [
		'as'	=> 	'dashboard.staffs.update',
		'uses'	=> 	'StaffController@update',
	]);

	// Get Staff edit page
	Route::get('/staffs/get-edit/{id}', [
		'as'	=> 	'dashboard.staffs.getPageEdit',
		'uses'	=> 	'StaffController@getPageEdit',
	]);


	// Staff Remove
	Route::post('/staffs/remove', [
		'as'	=> 	'dashboard.staffs.remove',
		'uses'	=> 	'StaffController@removeStaff',
	]);

	// Dashbaord Clients
	Route::get('/clients/all', [
		'as'	=> 	'dashboard.clients.all',
		'uses'	=> 	'ClientController@allClients',
	])->middleware('staffPermission');

	Route::post('/clients/create', [
		'as'	=> 	'dashboard.clients.create',
		'uses'	=> 	'ClientController@create',
	]);

	Route::post('/clients/remove', [
		'as'	=> 	'dashboard.clients.remove',
		'uses'	=> 	'ClientController@removeClient',
	]);



	///////////////////////////////////
	// Dashboard Settings Page Route //
	///////////////////////////////////

	// Settings page
	Route::get('/settings', [
		'as'	=> 	'dashboard.settings.index',
		'uses'	=> 	'SettingsController@index',
	]);

	// General Site Settings
	Route::post('/general/settings', [
		'as'	=> 	'dashboard.general.settings',
		'uses'	=> 	'SettingsController@generalSettings',
	]);

	// Theme Update Settings
	Route::post('/theme/update', [
		'as'	=> 	'dashboard.theme.update',
		'uses'	=> 	'SettingsController@themeUpdate',
	]);

	// Add  Department
	Route::post('/add/department', [
		'as'	=> 	'dashboard.add.department',
		'uses'	=> 	'SettingsController@addDepartment',
	]);

	// Edit  Department
	Route::post('/edit/department/{id}', [
		'as'	=> 	'dashboard.edit.department',
		'uses'	=> 	'SettingsController@editDepartment',
	]);

	// Remove  Department
	Route::post('/remove/department/{id}', [
		'as'	=> 	'dashboard.remove.department',
		'uses'	=> 	'SettingsController@removeDepartment',
	]);

	// Theme Update Settings
	Route::post('/app/settings', [
		'as'	=> 	'dashboard.app.settings',
		'uses'	=> 	'SettingsController@appSettings',
	]);




	///////////////////////
	// APPLICATIO UPDATE //
	///////////////////////

	Route::get('/update', [
		'as'	=> 	'dashboard.update',
		'uses'	=> 	'UpdateController@index',
	])->middleware('role:admin');


});

app/Models/Ticket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\User;
use App\Models\Reply;
use App\Models\Department;


class Ticket extends Model
{
    protected $fillable = ['user_id', 'department_id', 'name', 'message',
    'email','app_name','app_version','os_version','phone_model'];


    /**
     *
     * Ticket belongs to the user
     * @return App\Models\User
     *
     */
    public  function user()
    {
        return $this->belongsTo(User::class);
    }


    /**
     *
     * Ticket has many replies
     * @return App\Models\Reply
     *
     */
    public function replies()
    {
        return $this->hasMany(Reply::class);
    }



    /**
     *
     * Ticket belongs to the department
     * @return App\Models\Department
     *
     */
    public function department()
    {
        return $this->belongsTo(Department::class);
    }


    /**
     *
     * Get the department name
     * @return App\Models\Department
     * 
     *
     */
    public function getDepartment(  )
    {   
        $department =  $this->attributes['department_id'];

        if( $department ) {
            return $this->department->name;
        } else {
            return 'No department.';
        }
    }

    /**
     *
     * Format the subject
     * @return string
     *
     */
    public function FormatSubject(  )
    {   
        $value =  $this->attributes['name'];
        return str_replace(' ', '-', $value);
    }


    /**
     *
     * Reformat the subject
     * @param $subject
     * @return string
     *
     */
    public static function reformatTicket( $subject )
    {   
        return str_replace('-', ' ', $subject);
    }



    /**
     *
     * Get the assigned user
     * @return App\Models\User
     *
     */
    public function getAssignedStaff()
    {
        $assigned_to = $this->attributes['assigned_to'];

        if( $assigned_to == 0) {
            return trans('messages.singleTicket.notAssignedYet');
        } else {
            $user = User::find($assigned_to);

            if( $user ) {
                return $user->fullName() ;
            }
        }
    }

    /**
     *
     * Get the assigned user
     * @return App\Models\User
     *
     */
    public function getSolvedBy()
    {
        $solved_by = $this->attributes['solved_by'];

        if( $solved_by == 0) {
            return 'Not solved yet.';
        } else {
            $user = User::find($solved_by);

            if( $user ) {
                return $user->fullName();
            }
        }
    }


}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Models\Role;
use App\Models\Ticket;
use App\Models\Visitor;
use App\Models\Department;
use App\Http\Requests;
use App\Http\Controllers\AppBaseController;

class DashboardController extends AppBaseController
{

    /**
     *
     * @param  App\Models\Visitor
     * @return void
     * 
     */
    function __construct(Visitor $visitors)
    {
        parent::__construct();

        $this->visitors = $visitors;
    }



    /**
     *
     * Dashboard Page
     * @return App\Models\Ticket
     */
    public function index()
    {   
        // Get only 7 tickets for the dashboard
        $tickets = Ticket::take(7)->orderBy('created_at', 'DESC')->get();

        // Ticket Counting
        $all_ticket_counting = Ticket::count();
        $new_ticket_counting = Ticket::where('status', 'new')->count();
        $pending_ticket_counting = Ticket::where('status', 'pending')->count();
        $solved_ticket_counting = Ticket::where('status', 'solved')->count();

        // Get clients
        $role = Role::where('name', 'client')->first();
        $clients = Role::find($role->id)->users()->orderBy('created_at', 'DESC')->take(6)->get();

        // Get staffs
        $role = Role::where('name', 'staff')->first();
        $staffs = Role::find($role->id)->users()->orderBy('created_at', 'DESC')->take(7)->get();

        $departments = Department::lists('name', 'id');

        // $visitors = $this->visitors->all();
        // $clients = $this->visitors->whereMonth('created_at', '=', date('m'))->where('type', 'client')->get();
        // $visitors = $this->visitors->whereMonth('created_at', '=', date('m'))->where('type', 'guest')->get();

        $data = compact( 'tickets', 'departments',  'all_ticket_counting', 'new_ticket_counting','pending_ticket_counting', 'solved_ticket_counting', 'clients', 'staffs');

        return view('dashboard.home', $data);
    }



    /**
     *
     * Return the authenticated user as JSON
     * @return App\Models\User
     */
    public function getAuthUser()
    {
        if( \Auth::check() ) {
            $user = \Auth::user();

            return \Response::json(['user' => $user]);
        }

    }
}

resources/views/partials/dashboard/add_staff_and_client.blade.php
        <!-- New Client   -->

        <div class="md-modal md-effect-10 hidden-xs" id="newClient" >
            <div class="md-content settings-tab new-staff-modal">
                
                <h4> {{ trans('messages.addNewClient.title') }} </h4>

                {{ Form::open(['route' => 'dashboard.clients.create', 'method' => 'post', 'id' => 'add_client_form']) }}

                    <div class="form-group first_name_group">
                        {{ Form::label(trans('messages.addNewClient.first_name')) }}
                        {{ Form::text('first_name', null, ['class' => 'form-control add_c_fn', 'placeholder' => trans('messages.addNewClient.placeholders.firstName')])}}
                    </div>

                    <div class="form-group last_name_group">
                        {{ Form::label(trans('messages.addNewClient.last_name')) }}
                        {{ Form::text('last_name', null, ['class' => 'form-control add_c_ln', 'placeholder' => trans('messages.addNewClient.placeholders.lastName')])}}
                    </div>

                    <div class="form-group email_group">
                        {{ Form::label(trans('messages.addNewClient.email')) }}
                        {{ Form::email('email', null, ['class' => 'form-control add_c_e', 'placeholder' => trans('messages.addNewClient.placeholders.email')])}}
                    </div>


                    <div class="form-group password_group">
                        {{ Form::label(trans('messages.addNewClient.password')) }}
                        {{ Form::password('password', ['class' => 'form-control add_c_p'])}}
                    </div>

                    <div class="form-group client_img_g">
                        <label for="client_img"> {{ trans('messages.addNewClient.clientImage') }}</label>
                        <input type="file" name="client_img" id="file-2" class="inputfile inputfile-2" data-multiple-caption="{count} files selected" multiple />
                        <label for="file-2"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg> <span> {{ trans('messages.addNewClient.placeholders.file') }} </span></label>
                    </div>

                    <div class="form-status client_form_status"></div>


                    <div class="form-group  submit-btns">
                        <button type="submit" class="btn btn-success add_client_btn"> {{ trans('messages.addNewClient.addClientBtn') }} </button>
                    </div>

                {{ Form::close() }}

                <button class="md-close"><i class="fa fa-times"></i></button>

            </div>
        </div>
        

        <!-- New staff overlay -->

        <div class="md-modal md-effect-10  hidden-xs" id="newStaff">
            <div class="md-content settings-tab new-staff-modal">
                <h4>{{ trans('messages.addNewStaff.title') }}</h4>

                {{ Form::open(['route' => 'dashboard.staffs.create', 'method' => 'post', 'id' => 'add_staffs_form']) }}

                    <div class="form-group staff_first_name_group">
                        {{ Form::label( trans('messages.addNewStaff.firstName') ) }}
                        {{ Form::text('first_name', null, ['class' => 'form-control staff_first_name', 'placeholder' => trans('messages.addNewStaff.placeholders.first_name')])}}
                    </div>

                    <div class="form-group staff_email_group">
                        {{ Form::label( trans('messages.addNewStaff.email') ) }}
                        {{ Form::email('email', null, ['class' => 'form-control staff_email', 'placeholder' => trans('messages.addNewStaff.placeholders.email')])}}
                    </div>


                    <div class="form-group staff_password_group">
                        {{ Form::label( trans('messages.addNewStaff.password') ) }}
                        {{ Form::password('password', ['class' => 'form-control staff_password'])}}
                    </div>

                    <div class="form-group staff_img_g">
                        <label for="staff_img"> {{trans('messages.addNewStaff.staffImage') }}</label>
                        <input type="file" name="staff_img" id="file-3" class="inputfile inputfile-3" data-multiple-caption="{count} files selected" multiple />
                        <label for="file-3"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg> <span>
                        {{ trans('messages.addNewStaff.placeholders.file') }}</span></label>
                    </div>

                    <div class="form-group staff_department_group">
                        {{ Form::label('department_id', trans('messages.addNewStaff.department')) }}
                        {{ Form::select('department_id', $departments, null, ['class' => 'form-control staff_department'])}}
                    </div>

                    <div class="form-group role_group">
                        {{ Form::label( trans('messages.addNewStaff.roleName') )}}
                        {{ Form::text('role_name', null, ['class' => 'form-control staff_role', 'placeholder' => trans('messages.addNewStaff.placeholders.role_name')])}}
                    </div>


                    <div class="form-status staff_form_status"></div>


                    <div class="form-group  submit-btns">
                        <button type="submit" class="btn btn-success">{{ trans('messages.addNewStaff.addStaffBtn') }}</button>
                    </div>
                {{ Form::close() }}
                

                <button class="md-close"><i class="fa fa-times"></i></button>

            </div>
        </div>

resources/views/partials/dashboard/statistics.blade.php
<script>
$(document).ready(function() {

    //--------------
    //- AREA CHART -
    //--------------

    // Get context with jQuery - using jQuery's .get() method.
    var areaChartCanvas = $("#statisticsChart").get(0).getContext("2d");
    // This will get the first returned node in the jQuery collection.
    var areaChart = new Chart(areaChartCanvas);
    
    var areaChartData = {
      labels: [
      
            @foreach($days as $day)
              {{ $day->created_at->format('d') }},
            @endforeach
      ],
      datasets: [
        {
          label: "Clients",
          fillColor: "#ff595e",
          strokeColor: "#ff595e",
          pointColor: "#ff595e",
          pointStrokeColor: "#c1c7d1",
          pointHighlightFill: "#fff",
          pointHighlightStroke: "rgba(220,220,220,1)",
          data: [

            @foreach($clients as $client)
              {{ $client->clientCount }},
            @endforeach
          ]
        },
        {
          label: "Guest",
          fillColor: "#3a88e5",
          strokeColor: "rgba(60,141,188,0.8)",
          pointColor: "#3a88e5",
          pointStrokeColor: "rgba(60,141,188,1)",
          pointHighlightFill: "#fff",
          pointHighlightStroke: "rgba(60,141,188,1)",
          data: [

            @foreach($guests as $guest)
              {{ $guest->guestCount }},
            @endforeach

          ]
        }
      ]
    };


    legend(document.getElementById("lineLegend"), areaChartData);

    var areaChartOptions = {
      //Boolean - If we should show the scale at all
      showScale: true,
      legend: true,
      //Boolean - Whether grid lines are shown across the chart
      scaleShowGridLines: false,
      //String - Colour of the grid lines
      scaleGridLineColor: "rgba(0,0,0,.05)",
      //Number - Width of the grid lines
      scaleGridLineWidth: 1,
      //Boolean - Whether to show horizontal lines (except X axis)
      scaleShowHorizontalLines: true,
      //Boolean - Whether to show vertical lines (except Y axis)
      scaleShowVerticalLines: true,
      //Boolean - Whether the line is curved between points
      bezierCurve: true,
      //Number - Tension of the bezier curve between points
      bezierCurveTension: 0.3,
      //Boolean - Whether to show a dot for each point
      pointDot: false,
      //Number - Radius of each point dot in pixels
      pointDotRadius: 4,
      //Number - Pixel width of point dot stroke
      pointDotStrokeWidth: 1,
      //Number - amount extra to add to the radius to cater for hit detection outside the drawn point
      pointHitDetectionRadius: 20,
      //Boolean - Whether to show a stroke for datasets
      datasetStroke: true,
      //Number - Pixel width of dataset stroke
      datasetStrokeWidth: 2,
      //Boolean - Whether to fill the dataset with a color
      datasetFill: true,
      //String - A legend template
      legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].lineColor%>\"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>",
      //Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container
      maintainAspectRatio: true,
      //Boolean - whether to make the chart responsive to window resizing
      responsive: true
    };

    //Create the line chart
    areaChart.Line(areaChartData, areaChartOptions);
  });
</script>

resources/views/partials/dashboard/ticket_information.blade.php
<!-- TICKET INFORMATAION -->
<div class="col-lg-4 col-md-12 ticket-information">
    <div class="ticket-box">
        <div class="ticket-header">
            <h4>Ticket information</h4>
        </div>
        <div class="ticket-info-body">
            <table class="table table-hover">
                <tr>
                    <th> {{ trans('messages.singleTicket.ticketID') }}</th>
                    <td>#{{ $ticket->id }}</td>
                </tr>
                <tr>
                    <th>{{ trans('messages.singleTicket.client') }}:</th>
                    <td>{{ $ticket->user->fullName() }}</td>
                </tr>


                <tr>
                    <th>App Name:</th>
                    <td>{{ $ticket->app_name }}</td>
                </tr>
                <tr>
                    <th>App Version:</th>
                    <td>{{ $ticket->app_version }}</td>
                </tr>
                <tr>
                    <th>OS Version:</th>
                    <td>{{ $ticket->os_version }}</td>
                </tr>
                <tr>
                    <th>Phone Model:</th>
                    <td>{{ $ticket->phone_model }}</td>
                </tr>

                <tr>
                    <th>{{ trans('messages.singleTicket.supportType') }}</th>
                    <td>{{ $ticket->getDepartment() }}</td>
                </tr>
                <tr>
                    <th>{{ trans('messages.singleTicket.ticketStatus') }}</th>
                    <td class="template-ticket-status"><span
                                class="status-{{ $ticket->status }} ">{{ ucwords($ticket->status) }}</span></td>
                </tr>
                <tr>
                    <th>{{ trans('messages.singleTicket.assignedTicket') }}</th>
                    <td class=" ticket-info-assigned-staff"> {{ $ticket->getAssignedStaff() }} </td>
                </tr>
                @if( $ticket->solved_by )
                    <tr class="solved_by_staff">
                        <th>{{ trans('messages.singleTicket.solvedBy') }}</th>
                        <td class=" ticket-info-solved-staff"> {{ $ticket->getSolvedBy() }} </td>
                    </tr>
                @endif
            </table>
        </div>
        <div class="ticket-info-footer">
            <div class="ticket-info-buttons">
                <div class="as-n-s">
                    <button data-modal="modal-5"
                            class="btn btn-info assign-new-trigger">{{ trans('messages.singleTicket.assignNewTicket') }}</button>

                    <div class="assign-staff-up-box up-info-box ">
                        <h3>{{ trans('messages.singleTicket.assignThisTicket') }}</h3>
                        <span class="up-box-cancel"><i class="fa fa-times"></i></span>

                        <span class="up-box-status assign_upbox"><i
                                    class="fa fa-circle-o-notch status-success"></i></span>

                        <!-- ASSIGN TICKET POPUP TO ASSIGN THIS TICKET TO STAFF -->
                        <div class="box-form-outer scrollbar">
                            {{ Form::open([
                                'route' => ['ticket.assign.user', $ticket->id], 
                                'method' => 'post', 
                                'id' => 'ticket_assign_user'
                            ]) }}

                            @if( count($staffs) )

                            @foreach($staffs as $staff)

                                    <!-- EACH STAFF IN THE LIST -->
                            <div class="media assign-user-media">
                                <label for="assign_user_{{ $staff->id }}">

                                    <div class="media-left">
                                        <img class="media-object" src="{{ $staff->profileImg(40) }}" alt="Ohidul Islam">
                                    </div>
                                    <div class="media-body">
                                        <h4 class="media-heading">{{ $staff->fullName() }}</h4>

                                        <p>{{ $staff->role_name }}</p>

                                        <div>
                                            <input
                                                    type="radio"
                                                    name="assign_user"
                                                    class="assign_user"
                                                    value="{{ $staff->id }}"
                                                    id="assign_user_{{ $staff->id }}"
                                                    {{ $staff->fullName() == $ticket->getAssignedStaff() ? 'checked' : '' }}
                                                    >
                                            <span class="input_radio"><i class="fa fa-check"></i></span>
                                        </div>
                                    </div>
                                </label>
                            </div>
                            @endforeach

                            @else
                                <div class="media">
                                    <label for="assign_user_none">

                                        <div class="media-body">
                                            <h4 class="media-heading">{{ trans('messages.singleTicket.noStaffsFound') }}</h4>
                                        </div>

                                    </label>
                                </div>
                                @endif


                                </form>
                        </div>
                    </div>
                </div>

                <div class="as-n-u">
                    <button class="btn btn-success update_status_trigger">{{ trans('messages.singleTicket.updateStatus') }}</button>

                    <div class="up-info-box update-status">
                        <h3>{{ trans('messages.singleTicket.updateTicketStatus') }}</h3>
                        <span class="up-box-cancel"><i class="fa fa-times"></i></span>
                        <span class="up-box-status statusUpBx"><i
                                    class="fa fa-circle-o-notch fa-spin status-success"></i></span>

                        <!-- UPDATE TICKET STATUS POPUP -->
                        <div class="box-form-outer">
                            {{ Form::open([
                                'route' => ['update.ticket.status', $ticket->id],
                                'method' => 'post',
                                'id' => 'ticket_assign_form'
                            ])}}

                                    <!-- UPDATE STATUS LIST -->
                            <div class="media">
                                <label for="ticket_status_solved">

                                    <div class="media-body">
                                        <h4 class="media-heading">{{ trans('messages.singleTicket.solved') }}</h4>

                                        <div>
                                            <input
                                                    type="radio"
                                                    name="ticket_status"
                                                    class="ticket_status {{ $ticket->status == 'solved' ? 'checked' : '' }} "
                                                    value="solved"
                                                    id="ticket_status_solved"
                                                    {{ $ticket->status == 'solved' ? 'checked' : '' }}
                                                    >
                                            <span class="input_radio"></span>
                                        </div>
                                    </div>
                                </label>
                            </div>

                            <!-- UPDATE STATUS LIST -->
                            <div class="media">
                                <label for="ticket_status_pending">

                                    <div class="media-body">
                                        <h4 class="media-heading">{{ trans('messages.singleTicket.pending') }}</h4>

                                        <div>
                                            <input
                                                    type="radio"
                                                    name="ticket_status"
                                                    class="ticket_status {{ $ticket->status == 'pending' ? 'checked' : '' }}"
                                                    value="pending"
                                                    id="ticket_status_pending"
                                                    {{ $ticket->status == 'pending' ? 'checked' : '' }}
                                                    >
                                            <span class="input_radio ticket_pending"></span>
                                        </div>
                                    </div>
                                </label>
                            </div>

                            {{ Form::close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>